using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;

namespace HttpApi.Controllers
{
  [ApiController]
  [Route("[controller]")]
  public class CountriesController : ControllerBase
  {
    [HttpGet]
    public IEnumerable<Country> Get()
    {
      return countries;
    }

    private static readonly Country[] countries = new[]
    {
      new Country {Description = "Afghanistan", Name = "AF"},
      new Country {Description = "Åland Islands", Name = "AX"},
      new Country {Description = "Albania", Name = "AL"},
      new Country {Description = "Algeria", Name = "DZ"},
      new Country {Description = "American Samoa", Name = "AS"},
      new Country {Description = "AndorrA", Name = "AD"},
      new Country {Description = "Angola", Name = "AO"},
      new Country {Description = "Anguilla", Name = "AI"},
      new Country {Description = "Antarctica", Name = "AQ"},
      new Country {Description = "Antigua and Barbuda", Name = "AG"},
      new Country {Description = "Argentina", Name = "AR"},
      new Country {Description = "Armenia", Name = "AM"},
      new Country {Description = "Aruba", Name = "AW"},
      new Country {Description = "Australia", Name = "AU"},
      new Country {Description = "Austria", Name = "AT"},
      new Country {Description = "Azerbaijan", Name = "AZ"},
      new Country {Description = "Bahamas", Name = "BS"},
      new Country {Description = "Bahrain", Name = "BH"},
      new Country {Description = "Bangladesh", Name = "BD"},
      new Country {Description = "Barbados", Name = "BB"},
      new Country {Description = "Belarus", Name = "BY"},
      new Country {Description = "Belgium", Name = "BE"},
      new Country {Description = "Belize", Name = "BZ"},
      new Country {Description = "Benin", Name = "BJ"},
      new Country {Description = "Bermuda", Name = "BM"},
      new Country {Description = "Bhutan", Name = "BT"},
      new Country {Description = "Bolivia", Name = "BO"},
      new Country {Description = "Bosnia and Herzegovina", Name = "BA"},
      new Country {Description = "Botswana", Name = "BW"},
      new Country {Description = "Bouvet Island", Name = "BV"},
      new Country {Description = "Brazil", Name = "BR"},
      new Country {Description = "British Indian Ocean Territory", Name = "IO"},
      new Country {Description = "Brunei Darussalam", Name = "BN"},
      new Country {Description = "Bulgaria", Name = "BG"},
      new Country {Description = "Burkina Faso", Name = "BF"},
      new Country {Description = "Burundi", Name = "BI"},
      new Country {Description = "Cambodia", Name = "KH"},
      new Country {Description = "Cameroon", Name = "CM"},
      new Country {Description = "Canada", Name = "CA"},
      new Country {Description = "Cape Verde", Name = "CV"},
      new Country {Description = "Cayman Islands", Name = "KY"},
      new Country {Description = "Central African Republic", Name = "CF"},
      new Country {Description = "Chad", Name = "TD"},
      new Country {Description = "Chile", Name = "CL"},
      new Country {Description = "China", Name = "CN"},
      new Country {Description = "Christmas Island", Name = "CX"},
      new Country {Description = "Cocos (Keeling) Islands", Name = "CC"},
      new Country {Description = "Colombia", Name = "CO"},
      new Country {Description = "Comoros", Name = "KM"},
      new Country {Description = "Congo", Name = "CG"},
      new Country {Description = "Congo, The Democratic Republic of the", Name = "CD"},
      new Country {Description = "Cook Islands", Name = "CK"},
      new Country {Description = "Costa Rica", Name = "CR"},
      new Country {Description = "Cote D\"Ivoire", Name = "CI"},
      new Country {Description = "Croatia", Name = "HR"},
      new Country {Description = "Cuba", Name = "CU"},
      new Country {Description = "Cyprus", Name = "CY"},
      new Country {Description = "Czech Republic", Name = "CZ"},
      new Country {Description = "Denmark", Name = "DK"},
      new Country {Description = "Djibouti", Name = "DJ"},
      new Country {Description = "Dominica", Name = "DM"},
      new Country {Description = "Dominican Republic", Name = "DO"},
      new Country {Description = "Ecuador", Name = "EC"},
      new Country {Description = "Egypt", Name = "EG"},
      new Country {Description = "El Salvador", Name = "SV"},
      new Country {Description = "Equatorial Guinea", Name = "GQ"},
      new Country {Description = "Eritrea", Name = "ER"},
      new Country {Description = "Estonia", Name = "EE"},
      new Country {Description = "Ethiopia", Name = "ET"},
      new Country {Description = "Falkland Islands (Malvinas)", Name = "FK"},
      new Country {Description = "Faroe Islands", Name = "FO"},
      new Country {Description = "Fiji", Name = "FJ"},
      new Country {Description = "Finland", Name = "FI"},
      new Country {Description = "France", Name = "FR"},
      new Country {Description = "French Guiana", Name = "GF"},
      new Country {Description = "French Polynesia", Name = "PF"},
      new Country {Description = "French Southern Territories", Name = "TF"},
      new Country {Description = "Gabon", Name = "GA"},
      new Country {Description = "Gambia", Name = "GM"},
      new Country {Description = "Georgia", Name = "GE"},
      new Country {Description = "Germany", Name = "DE"},
      new Country {Description = "Ghana", Name = "GH"},
      new Country {Description = "Gibraltar", Name = "GI"},
      new Country {Description = "Greece", Name = "GR"},
      new Country {Description = "Greenland", Name = "GL"},
      new Country {Description = "Grenada", Name = "GD"},
      new Country {Description = "Guadeloupe", Name = "GP"},
      new Country {Description = "Guam", Name = "GU"},
      new Country {Description = "Guatemala", Name = "GT"},
      new Country {Description = "Guernsey", Name = "GG"},
      new Country {Description = "Guinea", Name = "GN"},
      new Country {Description = "Guinea-Bissau", Name = "GW"},
      new Country {Description = "Guyana", Name = "GY"},
      new Country {Description = "Haiti", Name = "HT"},
      new Country {Description = "Heard Island and Mcdonald Islands", Name = "HM"},
      new Country {Description = "Holy See (Vatican City State)", Name = "VA"},
      new Country {Description = "Honduras", Name = "HN"},
      new Country {Description = "Hong Kong", Name = "HK"},
      new Country {Description = "Hungary", Name = "HU"},
      new Country {Description = "Iceland", Name = "IS"},
      new Country {Description = "India", Name = "IN"},
      new Country {Description = "Indonesia", Name = "ID"},
      new Country {Description = "Iran, Islamic Republic Of", Name = "IR"},
      new Country {Description = "Iraq", Name = "IQ"},
      new Country {Description = "Ireland", Name = "IE"},
      new Country {Description = "Isle of Man", Name = "IM"},
      new Country {Description = "Israel", Name = "IL"},
      new Country {Description = "Italy", Name = "IT"},
      new Country {Description = "Jamaica", Name = "JM"},
      new Country {Description = "Japan", Name = "JP"},
      new Country {Description = "Jersey", Name = "JE"},
      new Country {Description = "Jordan", Name = "JO"},
      new Country {Description = "Kazakhstan", Name = "KZ"},
      new Country {Description = "Kenya", Name = "KE"},
      new Country {Description = "Kiribati", Name = "KI"},
      new Country {Description = "Korea, Democratic People\"S Republic of", Name = "KP"},
      new Country {Description = "Korea, Republic of", Name = "KR"},
      new Country {Description = "Kuwait", Name = "KW"},
      new Country {Description = "Kyrgyzstan", Name = "KG"},
      new Country {Description = "Lao People\"S Democratic Republic", Name = "LA"},
      new Country {Description = "Latvia", Name = "LV"},
      new Country {Description = "Lebanon", Name = "LB"},
      new Country {Description = "Lesotho", Name = "LS"},
      new Country {Description = "Liberia", Name = "LR"},
      new Country {Description = "Libyan Arab Jamahiriya", Name = "LY"},
      new Country {Description = "Liechtenstein", Name = "LI"},
      new Country {Description = "Lithuania", Name = "LT"},
      new Country {Description = "Luxembourg", Name = "LU"},
      new Country {Description = "Macao", Name = "MO"},
      new Country {Description = "Macedonia, The Former Yugoslav Republic of", Name = "MK"},
      new Country {Description = "Madagascar", Name = "MG"},
      new Country {Description = "Malawi", Name = "MW"},
      new Country {Description = "Malaysia", Name = "MY"},
      new Country {Description = "Maldives", Name = "MV"},
      new Country {Description = "Mali", Name = "ML"},
      new Country {Description = "Malta", Name = "MT"},
      new Country {Description = "Marshall Islands", Name = "MH"},
      new Country {Description = "Martinique", Name = "MQ"},
      new Country {Description = "Mauritania", Name = "MR"},
      new Country {Description = "Mauritius", Name = "MU"},
      new Country {Description = "Mayotte", Name = "YT"},
      new Country {Description = "Mexico", Name = "MX"},
      new Country {Description = "Micronesia, Federated States of", Name = "FM"},
      new Country {Description = "Moldova, Republic of", Name = "MD"},
      new Country {Description = "Monaco", Name = "MC"},
      new Country {Description = "Mongolia", Name = "MN"},
      new Country {Description = "Montserrat", Name = "MS"},
      new Country {Description = "Morocco", Name = "MA"},
      new Country {Description = "Mozambique", Name = "MZ"},
      new Country {Description = "Myanmar", Name = "MM"},
      new Country {Description = "Namibia", Name = "NA"},
      new Country {Description = "Nauru", Name = "NR"},
      new Country {Description = "Nepal", Name = "NP"},
      new Country {Description = "Netherlands", Name = "NL"},
      new Country {Description = "Netherlands Antilles", Name = "AN"},
      new Country {Description = "New Caledonia", Name = "NC"},
      new Country {Description = "New Zealand", Name = "NZ"},
      new Country {Description = "Nicaragua", Name = "NI"},
      new Country {Description = "Niger", Name = "NE"},
      new Country {Description = "Nigeria", Name = "NG"},
      new Country {Description = "Niue", Name = "NU"},
      new Country {Description = "Norfolk Island", Name = "NF"},
      new Country {Description = "Northern Mariana Islands", Name = "MP"},
      new Country {Description = "Norway", Name = "NO"},
      new Country {Description = "Oman", Name = "OM"},
      new Country {Description = "Pakistan", Name = "PK"},
      new Country {Description = "Palau", Name = "PW"},
      new Country {Description = "Palestinian Territory, Occupied", Name = "PS"},
      new Country {Description = "Panama", Name = "PA"},
      new Country {Description = "Papua New Guinea", Name = "PG"},
      new Country {Description = "Paraguay", Name = "PY"},
      new Country {Description = "Peru", Name = "PE"},
      new Country {Description = "Philippines", Name = "PH"},
      new Country {Description = "Pitcairn", Name = "PN"},
      new Country {Description = "Poland", Name = "PL"},
      new Country {Description = "Portugal", Name = "PT"},
      new Country {Description = "Puerto Rico", Name = "PR"},
      new Country {Description = "Qatar", Name = "QA"},
      new Country {Description = "Reunion", Name = "RE"},
      new Country {Description = "Romania", Name = "RO"},
      new Country {Description = "Russian Federation", Name = "RU"},
      new Country {Description = "RWANDA", Name = "RW"},
      new Country {Description = "Saint Helena", Name = "SH"},
      new Country {Description = "Saint Kitts and Nevis", Name = "KN"},
      new Country {Description = "Saint Lucia", Name = "LC"},
      new Country {Description = "Saint Pierre and Miquelon", Name = "PM"},
      new Country {Description = "Saint Vincent and the Grenadines", Name = "VC"},
      new Country {Description = "Samoa", Name = "WS"},
      new Country {Description = "San Marino", Name = "SM"},
      new Country {Description = "Sao Tome and Principe", Name = "ST"},
      new Country {Description = "Saudi Arabia", Name = "SA"},
      new Country {Description = "Senegal", Name = "SN"},
      new Country {Description = "Serbia and Montenegro", Name = "CS"},
      new Country {Description = "Seychelles", Name = "SC"},
      new Country {Description = "Sierra Leone", Name = "SL"},
      new Country {Description = "Singapore", Name = "SG"},
      new Country {Description = "Slovakia", Name = "SK"},
      new Country {Description = "Slovenia", Name = "SI"},
      new Country {Description = "Solomon Islands", Name = "SB"},
      new Country {Description = "Somalia", Name = "SO"},
      new Country {Description = "South Africa", Name = "ZA"},
      new Country {Description = "South Georgia and the South Sandwich Islands", Name = "GS"},
      new Country {Description = "Spain", Name = "ES"},
      new Country {Description = "Sri Lanka", Name = "LK"},
      new Country {Description = "Sudan", Name = "SD"},
      new Country {Description = "Suriname", Name = "SR"},
      new Country {Description = "Svalbard and Jan Mayen", Name = "SJ"},
      new Country {Description = "Swaziland", Name = "SZ"},
      new Country {Description = "Sweden", Name = "SE"},
      new Country {Description = "Switzerland", Name = "CH"},
      new Country {Description = "Syrian Arab Republic", Name = "SY"},
      new Country {Description = "Taiwan, Province of China", Name = "TW"},
      new Country {Description = "Tajikistan", Name = "TJ"},
      new Country {Description = "Tanzania, United Republic of", Name = "TZ"},
      new Country {Description = "Thailand", Name = "TH"},
      new Country {Description = "Timor-Leste", Name = "TL"},
      new Country {Description = "Togo", Name = "TG"},
      new Country {Description = "Tokelau", Name = "TK"},
      new Country {Description = "Tonga", Name = "TO"},
      new Country {Description = "Trinidad and Tobago", Name = "TT"},
      new Country {Description = "Tunisia", Name = "TN"},
      new Country {Description = "Turkey", Name = "TR"},
      new Country {Description = "Turkmenistan", Name = "TM"},
      new Country {Description = "Turks and Caicos Islands", Name = "TC"},
      new Country {Description = "Tuvalu", Name = "TV"},
      new Country {Description = "Uganda", Name = "UG"},
      new Country {Description = "Ukraine", Name = "UA"},
      new Country {Description = "United Arab Emirates", Name = "AE"},
      new Country {Description = "United Kingdom", Name = "GB"},
      new Country {Description = "United States", Name = "US"},
      new Country {Description = "United States Minor Outlying Islands", Name = "UM"},
      new Country {Description = "Uruguay", Name = "UY"},
      new Country {Description = "Uzbekistan", Name = "UZ"},
      new Country {Description = "Vanuatu", Name = "VU"},
      new Country {Description = "Venezuela", Name = "VE"},
      new Country {Description = "Viet Nam", Name = "VN"},
      new Country {Description = "Virgin Islands, British", Name = "VG"},
      new Country {Description = "Virgin Islands, U.S.", Name = "VI"},
      new Country {Description = "Wallis and Futuna", Name = "WF"},
      new Country {Description = "Western Sahara", Name = "EH"},
      new Country {Description = "Yemen", Name = "YE"},
      new Country {Description = "Zambia", Name = "ZM"},
      new Country {Description = "Zimbabwe", Name = "ZW"}
    };    
  }
}
